FROM quay.io/solo-io/gloo-envoy-wrapper:1.3.7
WORKDIR /
COPY ./data /data
COPY envoy-config.yaml /config/envoy.yaml
COPY start-gateway-proxy.sh start.sh
RUN chmod +x start.sh
ENTRYPOINT []
CMD ./start.sh
